import {useEffect,useRef,useState} from "react";
import {ActivityIndicator,Modal,Pressable,ScrollView,StyleSheet,TextInput,View} from "react-native";
import {SafeAreaView} from "react-native-safe-area-context";
import {Text} from "../i18n/LocalizedText";
import {useAuth} from "../auth/AuthContext";
import {colors} from "../theme";
export type CustomerSelection={id?:string;name:string;phone:string};
export default function CustomerPicker({onClose,onSelect}:{onClose:()=>void;onSelect:(customer:CustomerSelection)=>void}){
 const auth=useAuth(),api=useRef(auth.api);api.current=auth.api;
 const [search,setSearch]=useState(""),[items,setItems]=useState<CustomerSelection[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[adding,setAdding]=useState(false),[name,setName]=useState(""),[phone,setPhone]=useState("");
 useEffect(()=>{let active=true;const timer=setTimeout(async()=>{setLoading(true);setError("");try{const rows=await api.current<CustomerSelection[]>(`/customers${search.trim()?`?q=${encodeURIComponent(search.trim())}`:""}`);if(active)setItems(rows)}catch(e){if(active)setError((e as Error).message)}finally{if(active)setLoading(false)}},250);return()=>{active=false;clearTimeout(timer)}},[search,auth.session?.businessId]);
 return <Modal visible transparent animationType="slide" onRequestClose={onClose}><View style={s.overlay}><SafeAreaView style={s.sheet}><View style={s.row}><Text style={s.title}>{adding?"Add Customer":"Choose Customer"}</Text><Pressable accessibilityRole="button" onPress={onClose}><Text style={s.action}>Close</Text></Pressable></View><ScrollView style={s.list} keyboardShouldPersistTaps="handled" contentContainerStyle={s.content}>
 {adding?<><Text>Customer name *</Text><TextInput accessibilityLabel="Customer name" value={name} onChangeText={setName} style={s.input}/><Text>Phone number (optional)</Text><TextInput accessibilityLabel="Phone number" value={phone} onChangeText={setPhone} keyboardType="phone-pad" style={s.input}/><Pressable disabled={!name.trim()} onPress={()=>onSelect({name:name.trim(),phone:phone.trim()})} style={[s.button,!name.trim()&&s.disabled]}><Text style={s.buttonText}>Use Customer</Text></Pressable><Pressable onPress={()=>setAdding(false)}><Text style={s.action}>Back to customers</Text></Pressable></>:<>{loading?<ActivityIndicator color={colors.primary}/>:error?<Text style={s.error}>{error}</Text>:items.length?items.map(customer=><Pressable key={customer.id??customer.phone} onPress={()=>onSelect(customer)} style={s.item}><Text style={s.name}>{customer.name}</Text><Text>{customer.phone}</Text></Pressable>):<Text>No customers found.</Text>}</>}
 </ScrollView>{!adding&&<View style={s.footer}><TextInput accessibilityLabel="Search customers" placeholder="Search by name or phone" value={search} onChangeText={setSearch} style={s.input}/><Pressable onPress={()=>setAdding(true)} style={s.button}><Text style={s.buttonText}>+ Add New Customer</Text></Pressable></View>}</SafeAreaView></View></Modal>
}
const s=StyleSheet.create({overlay:{flex:1,justifyContent:"center",alignItems:"center",padding:16,backgroundColor:colors.overlay},sheet:{width:"100%",maxWidth:520,maxHeight:"85%",backgroundColor:colors.white,borderRadius:18,padding:16,gap:16},row:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},title:{fontSize:18,fontWeight:"700",color:colors.heading},list:{flexShrink:1},footer:{flexShrink:0,gap:12,borderTopWidth:1,borderTopColor:colors.divider,paddingTop:12},content:{gap:12},input:{minHeight:44,borderWidth:1,borderColor:colors.border,borderRadius:10,paddingHorizontal:12,color:colors.heading},item:{paddingVertical:12,borderBottomWidth:1,borderBottomColor:colors.divider,gap:4},name:{fontWeight:"700",color:colors.heading},action:{color:colors.primaryDark,fontWeight:"600"},button:{minHeight:44,justifyContent:"center",alignItems:"center",backgroundColor:colors.primary,borderRadius:10},buttonText:{color:colors.white,fontWeight:"700"},disabled:{opacity:.5},error:{color:colors.dangerText}});
