import { Text } from "../i18n/LocalizedText";
import {Ionicons} from "@expo/vector-icons";import {useEffect,useMemo,useState} from "react";
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, TextInput, useWindowDimensions, View } from "react-native";
import {useSafeAreaInsets} from "react-native-safe-area-context";
import {useAuth} from "../auth/AuthContext";
import {colors} from "../theme";
export type SupplierResult={id:string;name:string;phone:string|null;address:string|null;country:string|null};
const countries=["All","Bangladesh","China","India","Other"];
export default function SupplierPicker({open,onClose,onSelect,selectedId}:{open:boolean;onClose:()=>void;onSelect:(v:SupplierResult)=>void;selectedId?:string|null}){
 const auth=useAuth(),{width}=useWindowDimensions(),insets=useSafeAreaInsets(),desktop=width>=768;const [search,setSearch]=useState(""),[country,setCountry]=useState("All"),[items,setItems]=useState<SupplierResult[]>([]),[loading,setLoading]=useState(false),[addOpen,setAddOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");const [form,setForm]=useState({name:"",phone:"",address:"",country:"Bangladesh"});
 useEffect(()=>{if(!open)return;const timer=setTimeout(async()=>{setLoading(true);try{const p=new URLSearchParams();if(search.trim())p.set("search",search.trim());if(country!=="All"&&country!=="Other")p.set("country",country);let rows=await auth.api<SupplierResult[]>(`/suppliers${p.size?`?${p}`:""}`);if(country==="Other")rows=rows.filter(x=>!!x.country&&!countries.includes(x.country));setItems(rows)}finally{setLoading(false)}},250);return()=>clearTimeout(timer)},[open,search,country,auth.session?.businessId]);
 const groups=useMemo(()=>items.reduce<Record<string,SupplierResult[]>>((a,x)=>{const k=x.name[0]?.toUpperCase()||"#";(a[k]||=[]).push(x);return a},{}),[items]);
 const save=async()=>{if(!form.name.trim())return;setSaving(true);setError("");try{const x=await auth.api<SupplierResult>("/suppliers",{method:"POST",body:JSON.stringify({...form,name:form.name.trim(),phone:form.phone.trim()||null,address:form.address.trim()||null,notes:null})});setAddOpen(false);setForm({name:"",phone:"",address:"",country:"Bangladesh"});onSelect(x);onClose()}catch(e){setError((e as Error).message)}finally{setSaving(false)}};
 const panel=[s.panel,desktop?s.desktop:s.mobile,!desktop&&{paddingBottom:insets.bottom}];
 return <><Modal visible={open} transparent animationType={desktop?"fade":"slide"} onRequestClose={onClose}><View style={[s.overlay,!desktop&&s.mobileOverlay]}><View style={panel}>{!desktop&&<View style={s.handle}/>}<View style={s.head}><Text style={s.title}>Choose Supplier</Text><Pressable onPress={()=>setAddOpen(true)} style={s.add}><Text style={s.addText}>+ Add Supplier</Text></Pressable><Pressable onPress={onClose} style={s.icon}><Ionicons name="close" size={23} color={colors.secondary}/></Pressable></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}>{countries.map(x=><Pressable key={x} onPress={()=>setCountry(x)} style={[s.chip,country===x&&s.chipOn]}><Text style={[s.chipText,country===x&&s.chipTextOn]}>{x}</Text></Pressable>)}</ScrollView><ScrollView keyboardShouldPersistTaps="handled">{loading?<ActivityIndicator color={colors.primary} style={s.loading}/>:Object.keys(groups).sort().map(k=><View key={k}><Text style={s.section}>{k}</Text>{groups[k].map(x=><Pressable key={x.id} onPress={()=>{onSelect(x);onClose()}} style={[s.row,x.id===selectedId&&s.selected]}><View style={s.grow}><Text style={[s.name,x.id===selectedId&&s.selectedName]}>{x.name}</Text>{x.country&&<Text style={s.country}>{x.country}</Text>}{x.address&&<Text numberOfLines={1} style={s.meta}>📍 {x.address}</Text>}{x.phone&&<Text style={s.meta}>{x.phone}</Text>}</View>{x.id===selectedId&&<Ionicons name="checkmark-circle" size={20} color={colors.primary}/>}</Pressable>)}</View>)}{!loading&&!items.length&&<Text style={s.empty}>No suppliers found in this country.</Text>}</ScrollView><View style={s.search}><Ionicons name="search-outline" size={18} color={colors.muted}/><TextInput value={search} onChangeText={setSearch} placeholder="Search supplier" placeholderTextColor={colors.muted} style={s.searchInput}/></View></View></View></Modal>
 <Modal visible={addOpen} transparent animationType={desktop?"fade":"slide"} onRequestClose={()=>setAddOpen(false)}><View style={[s.overlay,!desktop&&s.mobileOverlay]}><View style={[s.panel,desktop?s.addDesktop:s.addMobile,!desktop&&{paddingBottom:insets.bottom}]}>{!desktop&&<View style={s.handle}/>}<View style={s.head}><Text style={s.title}>Add Supplier</Text><Pressable onPress={()=>setAddOpen(false)} style={s.icon}><Ionicons name="close" size={23} color={colors.secondary}/></Pressable></View><ScrollView contentContainerStyle={s.form}><Label>Name *</Label><TextInput value={form.name} onChangeText={name=>setForm(v=>({...v,name}))} style={s.input}/><Label>Country</Label><ScrollView horizontal contentContainerStyle={s.formCountries}>{countries.slice(1).map(x=><Pressable key={x} onPress={()=>setForm(v=>({...v,country:x}))} style={[s.chip,form.country===x&&s.chipOn]}><Text style={[s.chipText,form.country===x&&s.chipTextOn]}>{x}</Text></Pressable>)}</ScrollView><Label>Mobile number</Label><TextInput value={form.phone} onChangeText={phone=>setForm(v=>({...v,phone}))} keyboardType="phone-pad" style={s.input}/><Label>Address</Label><TextInput value={form.address} onChangeText={address=>setForm(v=>({...v,address}))} multiline style={[s.input,s.address]}/>{!!error&&<Text style={s.error}>{error}</Text>}<Pressable disabled={saving||!form.name.trim()} onPress={()=>void save()} style={[s.save,(saving||!form.name.trim())&&s.disabled]}>{saving?<ActivityIndicator color={colors.white}/>:<Text style={s.saveText}>Save Supplier</Text>}</Pressable></ScrollView></View></View></Modal></>;
}
function Label({children}:{children:string}){return <Text style={s.label}>{children}</Text>}
const s=StyleSheet.create({overlay:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:colors.overlay,padding:20},mobileOverlay:{justifyContent:"flex-end",padding:0},panel:{width:"100%",backgroundColor:colors.white,overflow:"hidden"},desktop:{maxWidth:560,height:"78%",borderRadius:18},mobile:{height:"86%",borderTopLeftRadius:20,borderTopRightRadius:20},addDesktop:{maxWidth:500,maxHeight:"80%",borderRadius:18},addMobile:{maxHeight:"88%",borderTopLeftRadius:20,borderTopRightRadius:20},handle:{width:42,height:4,alignSelf:"center",marginTop:9,borderRadius:2,backgroundColor:colors.divider},head:{minHeight:56,flexDirection:"row",alignItems:"center",gap:5,borderBottomWidth:1,borderBottomColor:colors.divider,paddingHorizontal:14},title:{flex:1,textAlign:"left",color:colors.heading,fontSize:16,fontWeight:"700"},add:{padding:8},addText:{color:colors.primaryDark,fontSize:12,fontWeight:"700"},icon:{width:36,height:38,alignItems:"center",justifyContent:"center"},filters:{gap:7,padding:10},chip:{height:32,justifyContent:"center",paddingHorizontal:13,borderRadius:16,borderWidth:1,borderColor:colors.border,backgroundColor:colors.cardSecondary},chipOn:{backgroundColor:colors.primary,borderColor:colors.primary},chipText:{color:colors.secondary,fontSize:12,fontWeight:"600"},chipTextOn:{color:colors.white},loading:{margin:28},section:{paddingHorizontal:14,paddingVertical:6,color:colors.primaryDark,backgroundColor:colors.primaryLight,fontSize:10,fontWeight:"800"},row:{minHeight:62,flexDirection:"row",alignItems:"center",paddingHorizontal:14,paddingVertical:9,borderBottomWidth:1,borderBottomColor:colors.divider},selected:{backgroundColor:colors.primaryLight},grow:{flex:1,minWidth:0},name:{color:colors.heading,fontSize:13,fontWeight:"700"},selectedName:{color:colors.primaryDark},country:{alignSelf:"flex-start",color:colors.primaryDark,fontSize:10,fontWeight:"700",backgroundColor:colors.primaryLight,paddingHorizontal:6,paddingVertical:2,borderRadius:8,marginTop:3},meta:{color:colors.muted,fontSize:10,marginTop:3},empty:{color:colors.muted,textAlign:"center",padding:28},search:{minHeight:45,flexDirection:"row",alignItems:"center",gap:8,margin:12,paddingHorizontal:12,borderWidth:1,borderColor:colors.border,borderRadius:11,backgroundColor:colors.cardSecondary},searchInput:{flex:1,height:43,color:colors.heading,outlineStyle:"none"} as never,form:{padding:16,gap:7},formCountries:{gap:7,paddingVertical:3},label:{color:colors.secondary,fontSize:12,fontWeight:"600",marginTop:5},input:{minHeight:46,borderWidth:1,borderColor:colors.border,borderRadius:11,paddingHorizontal:12,color:colors.heading,outlineStyle:"none"} as never,address:{minHeight:76,paddingTop:12,textAlignVertical:"top"},error:{color:colors.danger,fontSize:12},save:{minHeight:47,alignItems:"center",justifyContent:"center",borderRadius:12,backgroundColor:colors.primary,marginTop:10},saveText:{color:colors.white,fontSize:14,fontWeight:"700"},disabled:{opacity:.5}});
