// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ResellerApi.Data;

#nullable disable

namespace ResellerApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615000000_ExpandUserRoleColumn")]
    partial class ExpandUserRoleColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
