// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResellerApi.Data;

#nullable disable

namespace ResellerApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614000000_Phase3_ReceiveSessions")]
    partial class Phase3_ReceiveSessions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Target model is defined in AppDbContextModelSnapshot.cs
        }
    }
}
