// <auto-generated />
using ResellerApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ResellerApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614030000_Phase3_FixTripHeaderColumnNames")]
    partial class Phase3_FixTripHeaderColumnNames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
