// <auto-generated />
using ResellerApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ResellerApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614020000_Phase2_PriceHistoryIsApplied")]
    partial class Phase2_PriceHistoryIsApplied
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
