// <auto-generated />
using ResellerApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ResellerApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614010000_Phase3_TripHeaderFields")]
    partial class Phase3_TripHeaderFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
