import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    width: "100%",
    maxWidth: 768,
    alignSelf: "center",
    backgroundColor: "#f7f8fc",
  },
  header: {
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#e8ebf1",
    paddingHorizontal: 20,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  brandRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  logo: {
    width: 38,
    height: 38,
    borderRadius: 11,
    backgroundColor: "#4557d9",
    alignItems: "center",
    justifyContent: "center",
  },
  logoText: { color: "#fff", fontSize: 22, fontWeight: "800" },
  eyebrow: {
    color: "#929aaa",
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 1,
  },
  businessName: {
    color: "#172033",
    fontSize: 17,
    fontWeight: "800",
    marginTop: 2,
  },
  headerActions: { flexDirection: "row", alignItems: "center", gap: 9 },
  syncPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "#edf9f4",
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 20,
  },
  syncDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: "#12966f" },
  syncText: { fontSize: 10, color: "#187a5f", fontWeight: "700" },
  iconButton: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
  },
  notificationDot: {
    position: "absolute",
    right: 0,
    top: 0,
    minWidth: 15,
    height: 15,
    borderRadius: 8,
    backgroundColor: "#d34f5b",
    alignItems: "center",
    justifyContent: "center",
  },
  notificationText: { color: "#fff", fontSize: 9, fontWeight: "800" },
  avatar: {
    width: 31,
    height: 31,
    borderRadius: 16,
    backgroundColor: "#f0e8f8",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { color: "#8057b7", fontWeight: "800" },
  content: { padding: 20, paddingBottom: 110 },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  title: { color: "#172033", fontSize: 23, fontWeight: "400" },
  subtitle: { color: "#929aaa", fontSize: 12, marginTop: 4 },
  chevronButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#eef0ff",
    alignItems: "center",
    justifyContent: "center",
  },
  moneyStrip: { gap: 10, paddingBottom: 4 },
  moneyCard: {
    width: 157,
    minHeight: 142,
    borderRadius: 15,
    padding: 14,
    borderWidth: 1,
  },
  money_mint: { backgroundColor: "#eaf8f2", borderColor: "#d2eee3" },
  money_blue: { backgroundColor: "#edf3ff", borderColor: "#dbe6ff" },
  money_rose: { backgroundColor: "#fff0f1", borderColor: "#f8dadd" },
  money_amber: { backgroundColor: "#fff7e8", borderColor: "#f5e5bf" },
  cardIcon: {
    width: 33,
    height: 33,
    borderRadius: 10,
    backgroundColor: "#ffffff99",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 13,
  },
  moneyLabel: { color: "#657086", fontSize: 11, fontWeight: "600" },
  moneyValue: {
    color: "#172033",
    fontSize: 20,
    fontWeight: "800",
    marginTop: 5,
  },
  tapHint: { color: "#7e899c", fontSize: 10, marginTop: 5 },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 25,
    marginBottom: 11,
  },
  sectionTitle: { color: "#172033", fontSize: 15, fontWeight: "400" },
  sectionLink: { color: "#4557d9", fontSize: 11, fontWeight: "700" },
  statsGrid: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#e8ebf1",
    paddingVertical: 15,
  },
  stat: {
    flex: 1,
    alignItems: "center",
    borderRightWidth: 1,
    borderRightColor: "#edf0f4",
  },
  statValue: { fontSize: 21, fontWeight: "800" },
  statLabel: {
    color: "#7e899c",
    fontSize: 10,
    marginTop: 4,
    textAlign: "center",
  },
  actionGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  actionCard: {
    width: "47.5%",
    minHeight: 88,
    borderRadius: 14,
    padding: 14,
    justifyContent: "space-between",
  },
  actionLabel: { color: "#fff", fontWeight: "800", fontSize: 12 },
  attentionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 25,
    marginBottom: 11,
  },
  attentionTitle: { flexDirection: "row", alignItems: "center", gap: 7 },
  attentionCard: {
    backgroundColor: "#fff8eb",
    borderWidth: 1,
    borderColor: "#f4dfb5",
    borderRadius: 14,
    padding: 13,
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    marginBottom: 9,
  },
  attentionIcon: {
    width: 39,
    height: 39,
    borderRadius: 11,
    backgroundColor: "#fff0cf",
    alignItems: "center",
    justifyContent: "center",
  },
  attentionCopy: { flex: 1 },
  attentionHeadline: { color: "#263248", fontWeight: "800", fontSize: 12 },
  attentionDetail: { color: "#7e899c", fontSize: 11, marginTop: 4 },
  bottomBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 78,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#e8ebf1",
    flexDirection: "row",
    paddingBottom: 7,
  },
  tab: { flex: 1, alignItems: "center", justifyContent: "flex-end", gap: 4 },
  tabLabel: { color: "#929aaa", fontSize: 10, fontWeight: "600" },
  activeTabLabel: { color: "#4557d9" },
  activeTabIcon: {
    backgroundColor: "#eef0ff",
    width: 40,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  posTab: { paddingTop: 0 },
  posButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#4557d9",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 2,
    shadowColor: "#4557d9",
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
});
