import {Ionicons} from "@expo/vector-icons";
import {useEffect,useRef,useState} from "react";
import {ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,TextInput,View} from "react-native";
import {useAuth} from "../auth/AuthContext";
import {useLanguage} from "../i18n/LanguageContext";
import {Text} from "../i18n/LocalizedText";
import {colors} from "../theme";

type Settings={target_margin_pct?:string;overhead_mode?:string;refund_threshold?:string;low_stock_default?:string;return_policy_days?:string;selling_mode?:string};
type Key=keyof Settings;

export default function BusinessConfigScreen(){
 const auth=useAuth(),{t}=useLanguage(),apiRef=useRef(auth.api);apiRef.current=auth.api;
 const [targetMargin,setTargetMargin]=useState(""),[overheadMode,setOverheadMode]=useState("AUTO"),[refundThreshold,setRefundThreshold]=useState(""),[lowStockDefault,setLowStockDefault]=useState(""),[returnPolicyDays,setReturnPolicyDays]=useState(""),[sellingMode,setSellingMode]=useState("BOTH"),[loading,setLoading]=useState(true),[savingKey,setSavingKey]=useState<Key|null>(null),[savedKey,setSavedKey]=useState<Key|null>(null),[error,setError]=useState(""),[refresh,setRefresh]=useState(0);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const load=async()=>{setLoading(true);setError("");try{const value=await apiRef.current<Settings>("/settings");if(value.target_margin_pct)setTargetMargin(value.target_margin_pct);if(value.overhead_mode)setOverheadMode(value.overhead_mode);if(value.refund_threshold)setRefundThreshold(value.refund_threshold);if(value.low_stock_default)setLowStockDefault(value.low_stock_default);if(value.return_policy_days)setReturnPolicyDays(value.return_policy_days);if(value.selling_mode)setSellingMode(value.selling_mode)}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
 useEffect(()=>{void load();return()=>{if(timer.current)clearTimeout(timer.current)}},[refresh,auth.session?.businessId]);
 const save=async(key:Key,value:string)=>{setSavingKey(key);setError("");try{await apiRef.current("/settings",{method:"PUT",body:JSON.stringify({key,value})});setSavedKey(key);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setSavedKey(null),2000)}catch(e){setError((e as Error).message||t("settings.saveFailed"))}finally{setSavingKey(null)}};
 if(loading&&!targetMargin)return <View style={s.screen}><Header t={t}/><View style={s.state}><ActivityIndicator color={colors.primary}/><Text style={s.stateText}>Loading business settings…</Text></View></View>;
 return <View style={s.screen}><Header t={t}/><ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={()=>setRefresh(v=>v+1)} colors={[colors.primary]}/>} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">{!!error&&<View style={s.error}><Ionicons name="alert-circle-outline" size={17} color={colors.danger}/><Text style={s.errorText}>{error}</Text></View>}
 <ConfigCard icon="trending-up-outline" label={t("settings.targetMargin")} hint={t("settings.targetMarginHint")} settingKey="target_margin_pct" savingKey={savingKey} savedKey={savedKey} onSave={()=>void save("target_margin_pct",targetMargin)} t={t}><View style={s.inputRow}><TextInput value={targetMargin} onChangeText={setTargetMargin} keyboardType="decimal-pad" placeholder="e.g. 20" placeholderTextColor={colors.muted} style={[s.input,s.flex]}/><View style={s.suffix}><Text style={s.suffixText}>%</Text></View></View></ConfigCard>
 <ConfigCard icon="calculator-outline" label={t("settings.overheadMode")} settingKey="overhead_mode" savingKey={savingKey} savedKey={savedKey} onSave={()=>void save("overhead_mode",overheadMode)} t={t}><Segment options={[{value:"AUTO",label:t("settings.overheadAuto")},{value:"MANUAL",label:t("settings.overheadManual")}]} value={overheadMode} onChange={setOverheadMode}/></ConfigCard>
 <ConfigCard icon="shield-checkmark-outline" label={t("settings.refundThreshold")} hint={t("settings.refundThresholdHint")} settingKey="refund_threshold" savingKey={savingKey} savedKey={savedKey} onSave={()=>void save("refund_threshold",refundThreshold)} t={t}><TextInput value={refundThreshold} onChangeText={setRefundThreshold} keyboardType="decimal-pad" placeholder="e.g. 500" placeholderTextColor={colors.muted} style={s.input}/></ConfigCard>
 <ConfigCard icon="alert-circle-outline" label={t("settings.lowStockDefault")} hint={t("settings.lowStockHint")} settingKey="low_stock_default" savingKey={savingKey} savedKey={savedKey} onSave={()=>void save("low_stock_default",lowStockDefault)} t={t}><TextInput value={lowStockDefault} onChangeText={setLowStockDefault} keyboardType="decimal-pad" placeholder="e.g. 5" placeholderTextColor={colors.muted} style={s.input}/></ConfigCard>
 <ConfigCard icon="return-down-back-outline" label={t("settings.returnPolicyDays")} settingKey="return_policy_days" savingKey={savingKey} savedKey={savedKey} onSave={()=>void save("return_policy_days",returnPolicyDays)} t={t}><TextInput value={returnPolicyDays} onChangeText={setReturnPolicyDays} keyboardType="number-pad" placeholder="e.g. 7" placeholderTextColor={colors.muted} style={s.input}/></ConfigCard>
 <ConfigCard icon="storefront-outline" label={t("settings.sellingMode")} hint={t("settings.sellingModeHint")} settingKey="selling_mode" savingKey={savingKey} savedKey={savedKey} onSave={()=>void save("selling_mode",sellingMode)} t={t}><Segment options={[{value:"RETAIL",label:t("settings.sellingModeRetail")},{value:"WHOLESALE",label:t("settings.sellingModeWholesale")},{value:"BOTH",label:t("settings.sellingModeBoth")}]} value={sellingMode} onChange={setSellingMode}/></ConfigCard></ScrollView></View>
}
function Header({t}:{t:(key:string)=>string}){return <View style={s.header}><View style={s.headerIcon}><Ionicons name="options-outline" size={23} color={colors.primaryDark}/></View><View style={s.flex}><Text style={s.title}>{t("settings.configTitle")}</Text><Text style={s.subtitle}>Configure pricing, inventory and sales defaults</Text></View></View>}
function ConfigCard({icon,label,hint,children,settingKey,savingKey,savedKey,onSave,t}:{icon:keyof typeof Ionicons.glyphMap;label:string;hint?:string;children:React.ReactNode;settingKey:Key;savingKey:Key|null;savedKey:Key|null;onSave:()=>void;t:(key:string)=>string}){const saving=savingKey===settingKey,saved=savedKey===settingKey;return <View style={s.card}><View style={s.cardHeader}><View style={s.cardIcon}><Ionicons name={icon} size={18} color={colors.primaryDark}/></View><View style={s.flex}><Text style={s.cardTitle}>{label}</Text>{!!hint&&<Text style={s.hint}>{hint}</Text>}</View>{saved&&<View style={s.saved}><Ionicons name="checkmark-circle" size={16} color={colors.successText}/><Text style={s.savedText}>{t("settings.saved")}</Text></View>}</View>{children}<Pressable disabled={savingKey!==null} onPress={onSave} style={[s.save,savingKey!==null&&s.disabled]}>{saving?<ActivityIndicator size="small" color={colors.white}/>:<><Ionicons name="save-outline" size={15} color={colors.white}/><Text style={s.saveText}>{t("common.save")}</Text></>}</Pressable></View>}
function Segment({options,value,onChange}:{options:{value:string;label:string}[];value:string;onChange:(value:string)=>void}){return <View style={s.segment}>{options.map(option=><Pressable key={option.value} onPress={()=>onChange(option.value)} style={[s.segmentButton,value===option.value&&s.segmentOn]}><Text style={[s.segmentText,value===option.value&&s.segmentTextOn]}>{option.label}</Text></Pressable>)}</View>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},header:{minHeight:65,flexDirection:"row",alignItems:"center",gap:10,borderBottomWidth:1,borderBottomColor:colors.divider,backgroundColor:colors.white,paddingHorizontal:14},headerIcon:{width:40,height:40,borderRadius:12,alignItems:"center",justifyContent:"center",backgroundColor:colors.primaryLight},flex:{flex:1,minWidth:0},title:{fontSize:16,fontWeight:"800",color:colors.heading},subtitle:{fontSize:9,color:colors.muted,marginTop:2},content:{padding:14,paddingBottom:34,gap:11},card:{gap:11,borderWidth:1,borderColor:colors.divider,borderRadius:14,backgroundColor:colors.white,padding:13,shadowColor:colors.primary,shadowOpacity:.035,shadowRadius:8,shadowOffset:{width:0,height:2}},cardHeader:{flexDirection:"row",alignItems:"center",gap:9},cardIcon:{width:36,height:36,borderRadius:10,alignItems:"center",justifyContent:"center",backgroundColor:colors.primaryLight},cardTitle:{fontSize:12,fontWeight:"700",color:colors.heading},hint:{fontSize:9,lineHeight:13,color:colors.muted,marginTop:2},inputRow:{flexDirection:"row",alignItems:"center",gap:8},input:{minHeight:42,borderWidth:1,borderColor:colors.border,borderRadius:10,backgroundColor:colors.white,paddingHorizontal:11,color:colors.heading,fontSize:11,outlineStyle:"none"} as never,suffix:{width:42,height:42,alignItems:"center",justifyContent:"center",borderRadius:10,backgroundColor:colors.cardSecondary},suffixText:{fontSize:13,fontWeight:"800",color:colors.primaryDark},segment:{flexDirection:"row",borderWidth:1,borderColor:colors.divider,borderRadius:11,overflow:"hidden"},segmentButton:{flex:1,minHeight:43,alignItems:"center",justifyContent:"center",paddingHorizontal:5,backgroundColor:colors.white},segmentOn:{backgroundColor:colors.primary},segmentText:{fontSize:9,fontWeight:"700",color:colors.secondary,textAlign:"center"},segmentTextOn:{color:colors.white},save:{minHeight:38,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:5,borderRadius:9,backgroundColor:colors.primary},saveText:{fontSize:10,fontWeight:"700",color:colors.white},disabled:{opacity:.45},saved:{flexDirection:"row",alignItems:"center",gap:3,borderRadius:9,backgroundColor:colors.successBackground,paddingHorizontal:7,paddingVertical:5},savedText:{fontSize:8,fontWeight:"700",color:colors.successText},error:{flexDirection:"row",alignItems:"center",gap:7,borderRadius:10,backgroundColor:colors.dangerBackground,padding:10},errorText:{flex:1,fontSize:9,color:colors.dangerText},state:{flex:1,alignItems:"center",justifyContent:"center",gap:9},stateText:{fontSize:10,color:colors.secondary}});
