import PageTitle from "../components/PageTitle";
import { Text } from "../i18n/LocalizedText";
import { Ionicons } from "@expo/vector-icons";import { router } from "expo-router";import { useEffect, useState } from "react";import { ActivityIndicator, Pressable, ScrollView, StyleSheet, View } from "react-native";import { useAuth, type Branch } from "../auth/AuthContext";import { colors } from "../theme";import type { PurchaseDetail,SourceType } from "../types/purchases";
const options:{type:SourceType;label:string;desc:string;icon:React.ComponentProps<typeof Ionicons>["name"]}[]=[{type:"CHINA_TRIP",label:"China Trip",desc:"Import goods directly from China",icon:"airplane-outline"},{type:"ONLINE_WHOLESALE",label:"Online Wholesale",desc:"Buy from online wholesale platforms",icon:"cart-outline"},{type:"LOCAL_WHOLESALE",label:"Local Wholesale",desc:"Buy from local wholesale markets",icon:"storefront-outline"},{type:"AGENT",label:"Agent",desc:"Purchase through a sourcing agent",icon:"people-outline"},{type:"FACTORY_DIRECT",label:"Factory Direct",desc:"Buy directly from a factory",icon:"business-outline"},{type:"IMPORTER_DISTRIBUTOR",label:"Importer / Distributor",desc:"Buy from an importer or distributor",icon:"car-outline"},{type:"SOCIAL_SUPPLIER",label:"Social Supplier",desc:"Purchase through social media",icon:"chatbubbles-outline"},{type:"EXISTING_SUPPLIER_REORDER",label:"Existing Supplier Reorder",desc:"Order again from an existing supplier",icon:"repeat-outline"}];
const SOURCE_CODES:Record<SourceType,string>={CHINA_TRIP:"CT",ONLINE_WHOLESALE:"OW",ALIBABA:"AB",LOCAL_WHOLESALE:"LW",AGENT:"AG",FACTORY_DIRECT:"FD",IMPORTER_DISTRIBUTOR:"ID",SOCIAL_SUPPLIER:"SS",EXISTING_SUPPLIER_REORDER:"ER"};const defaultName=(sourceType:SourceType)=>{const d=new Date();const date=`${String(d.getDate()).padStart(2,"0")}${String(d.getMonth()+1).padStart(2,"0")}${String(d.getFullYear()).slice(-2)}`;return `PO-${SOURCE_CODES[sourceType]}-${date}`};
export default function NewPurchaseScreen(){const auth=useAuth();const [selected,setSelected]=useState<typeof options[number]|null>(null);const [name,setName]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [branches,setBranches]=useState<Branch[]>([]);
const [branchId,setBranchId]=useState("");
const [branchOpen,setBranchOpen]=useState(false);
const [branchesLoading,setBranchesLoading]=useState(true);
const [branchError,setBranchError]=useState("");
const [branchReload,setBranchReload]=useState(0);
useEffect(()=>{
  let live=true;
  setBranchesLoading(true);setBranchError("");setBranchId("");setBranches([]);setBranchOpen(false);
  auth.api<Branch[]>("/branches/mine").then(rows=>{
    if(!live)return;
    const active=rows.filter(branch=>branch.isActive!==false);
    setBranches(active);
    setBranchId(active.find(branch=>branch.id===auth.session?.branchId)?.id ?? (active.length===1?active[0].id:""));
    if(!active.length)setBranchError("No active purchase branch is available.");
  }).catch(e=>{if(live)setBranchError((e as Error).message)}).finally(()=>{if(live)setBranchesLoading(false)});
  return()=>{live=false};
},[auth.session?.businessId,auth.session?.branchId,branchReload]);
const choose=(o:typeof options[number])=>{setSelected(o);setName(defaultName(o.type))};const create=async()=>{if(!selected||busy||branchesLoading||!branchId||!!branchError||branchesLoading||!branchId||branchError)return;setBusy(true);setError("");try{const trip=await auth.api<PurchaseDetail>("/purchase-trips",{method:"POST",body:JSON.stringify({sourceType:selected.type,branchId,note:name||defaultName(selected.type)})});router.replace({pathname:"/more/purchases/[id]",params:{id:trip.id}})}catch(e){setError((e as Error).message)}finally{setBusy(false)}};return <View style={s.root}><View style={s.header}><PageTitle accessibilityRole="header" style={s.title}>Create Purchase Order</PageTitle></View><ScrollView contentContainerStyle={s.content}><View style={s.promptRow}><Text style={s.intro}>Where are you purchasing the products from?</Text>{selected&&<Pressable accessibilityRole="button" accessibilityLabel="Change purchase type" disabled={busy} onPress={()=>{setSelected(null);setName("");setError("")}} style={s.changeButton}><Text style={s.changeText}>Change</Text></Pressable>}</View><View key={selected ? `selected-${selected.type}` : "purchase-options"} style={s.grid}>{(selected?[selected]:options).map(o=><Pressable key={o.type} accessibilityRole="button" accessibilityLabel={o.label} accessibilityState={{ selected: selected?.type === o.type, disabled: busy }} disabled={busy} onPress={()=>choose(o)} style={[s.option,selected&&s.selectedOnly,selected?.type===o.type&&s.optionOn]}><Ionicons name={o.icon} size={28} color={colors.primaryDark} style={s.sourceIcon}/><Text style={s.optionTitle}>{o.label}</Text><Text style={s.optionDesc}>{o.desc}</Text>{selected?.type===o.type&&<View style={s.check}><Ionicons name="checkmark" size={13} color={colors.white}/></View>}</Pressable>)}</View>{selected&&<View><Text style={s.label}>PURCHASE ORDER NAME</Text><View style={s.readonlyName}><Ionicons name="lock-closed-outline" size={16} color={colors.muted}/><Text style={s.readonlyNameText}>{name}</Text></View><Text style={s.hint}>Generated automatically from the purchase source and date.</Text></View>}{selected&&<View>
{branchesLoading&&<ActivityIndicator color={colors.primary}/>}
{!!branchError&&<View><Text style={s.error}>{branchError}</Text><Pressable accessibilityRole="button" onPress={()=>setBranchReload(value=>value+1)} style={s.changeButton}><Text style={s.changeText}>Retry branches</Text></Pressable></View>}
{branches.length>1&&<View><Text style={s.label}>Purchase Branch</Text><Pressable accessibilityRole="button" accessibilityLabel="Purchase Branch" accessibilityState={{expanded:branchOpen,disabled:busy}} disabled={busy} onPress={()=>setBranchOpen(value=>!value)} style={s.readonlyName}><Ionicons name="business-outline" size={18} color={colors.primaryDark}/><Text style={[s.readonlyNameText,{flex:1}]}>{branches.find(branch=>branch.id===branchId)?.name??"Select branch"}</Text><Ionicons name={branchOpen?"chevron-up":"chevron-down"} size={18} color={colors.primaryDark}/></Pressable>
{branchOpen&&branches.map(branch=><Pressable key={branch.id} accessibilityRole="radio" accessibilityState={{checked:branch.id===branchId,disabled:busy}} disabled={busy} onPress={()=>{setBranchId(branch.id);setBranchOpen(false)}} style={[s.readonlyName,{marginTop:4}]}><Text style={[s.readonlyNameText,{flex:1}]}>{branch.name}</Text>{branch.id===branchId&&<Ionicons name="checkmark" size={18} color={colors.primary}/>}</Pressable>)}
</View>}
</View>}{!!error&&<Text style={s.error}>{error}</Text>}<Pressable disabled={!selected||busy||branchesLoading||!branchId||!!branchError} onPress={()=>void create()} style={[s.primary,(!selected||busy||branchesLoading||!branchId||!!branchError)&&s.disabled]}>{busy?<ActivityIndicator color={colors.white}/>:<Text style={s.primaryText}>Start Purchase Order</Text>}</Pressable></ScrollView></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.background},header:{minHeight:58,flexDirection:"row",alignItems:"center",gap:11,borderBottomWidth:1,borderBottomColor:colors.divider,backgroundColor:colors.white,paddingHorizontal:16},title:{color:colors.heading,fontSize:16,fontWeight:"700"},content:{gap:16,padding:16,paddingBottom:30},promptRow:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:10},intro:{flex:1,color:colors.secondary,fontSize:13},changeButton:{borderWidth:1,borderColor:colors.secondaryBorder,borderRadius:12,backgroundColor:colors.primaryLight,paddingHorizontal:10,paddingVertical:5},changeText:{color:colors.primaryDark,fontSize:10,fontWeight:"700"},grid:{flexDirection:"row",flexWrap:"wrap",gap:10},option:{width:"48.4%",minHeight:128,alignItems:"center",justifyContent:"center",borderWidth:2,borderColor:colors.border,borderRadius:16,backgroundColor:colors.cardSecondary,padding:14},optionOn:{borderColor:colors.primary,backgroundColor:colors.primaryLight},selectedOnly:{width:"100%",minHeight:112},sourceIcon:{marginBottom:8},optionTitle:{color:colors.heading,fontSize:13,fontWeight:"700",textAlign:"center"},optionDesc:{color:colors.muted,fontSize:10,lineHeight:14,marginTop:3,textAlign:"center"},check:{position:"absolute",right:10,top:10,width:21,height:21,alignItems:"center",justifyContent:"center",borderRadius:11,backgroundColor:colors.primary},label:{color:colors.muted,fontSize:10,fontWeight:"700",marginBottom:6},readonlyName:{minHeight:46,flexDirection:"row",alignItems:"center",gap:9,borderWidth:1,borderColor:colors.border,borderRadius:11,backgroundColor:colors.primaryLight,paddingHorizontal:12},readonlyNameText:{color:colors.heading,fontSize:13,fontWeight:"600"},hint:{color:colors.muted,fontSize:10,marginTop:5},primary:{minHeight:48,alignItems:"center",justifyContent:"center",borderRadius:12,backgroundColor:colors.primary},primaryText:{color:colors.white,fontSize:13,fontWeight:"700"},disabled:{opacity:.45},error:{color:colors.dangerText,backgroundColor:colors.dangerBackground,padding:10,borderRadius:9}});

