import {Ionicons} from "@expo/vector-icons";
import {useEffect,useRef,useState} from "react";
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,View} from "react-native";
import {useAuth} from "../auth/AuthContext";
import {useLanguage} from "../i18n/LanguageContext";
import {Text} from "../i18n/LocalizedText";
import {colors} from "../theme";

type ShopType="BIG_SUPERSHOP"|"SMALL_SHOWROOM"|"HAWKER_SHOP";
const choices:{value:ShopType;icon:string;channels:string[]}[]=[{value:"BIG_SUPERSHOP",icon:"🏢",channels:["POS","ONLINE"]},{value:"SMALL_SHOWROOM",icon:"🏪",channels:["HAWKER","ONLINE"]},{value:"HAWKER_SHOP",icon:"🧺",channels:["HAWKER","ONLINE"]}];
function fromChannels(channels?:string[]):ShopType|null{if(channels?.includes("POS"))return "BIG_SUPERSHOP";if(channels?.includes("HAWKER"))return "HAWKER_SHOP";return null}

export default function ShopTypeSettingsScreen(){
 const auth=useAuth(),{t}=useLanguage(),business=auth.session?.businesses.find(item=>item.id===auth.session?.businessId),saved=(business?.shopType as ShopType|undefined)??fromChannels(business?.salesChannels),[selected,setSelected]=useState<ShopType|null>(saved),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");const businessIdRef=useRef(auth.session?.businessId);
 useEffect(()=>{if(businessIdRef.current!==auth.session?.businessId){businessIdRef.current=auth.session?.businessId;setSelected(saved);setNotice("");setError("")}},[auth.session?.businessId,saved]);
 const save=async()=>{if(!selected)return;const choice=choices.find(item=>item.value===selected);if(!choice)return;setSaving(true);setError("");try{await auth.api("/onboarding/sales-channels",{method:"POST",body:JSON.stringify({salesChannels:choice.channels,shopType:selected})});await auth.updateCurrentBusinessSalesChannels(choice.channels,selected);setNotice(t("settings.shopTypeSaved"))}catch(e){setError((e as Error).message||t("onboarding.setSalesChannelsFailed"))}finally{setSaving(false)}};
 return <View style={s.screen}><View style={s.header}><View style={s.headerIcon}><Ionicons name="storefront-outline" size={23} color={colors.primaryDark}/></View><View style={s.flex}><Text style={s.title}>{t("settings.shopType")}</Text><Text style={s.headerSubtitle}>Choose how your shop sells products</Text></View></View><ScrollView contentContainerStyle={s.content}><View style={s.intro}><Text style={s.introTitle}>{t("onboarding.shopTypeTitle")}</Text><Text style={s.introText}>{t("onboarding.shopTypeSubtitle")}</Text></View>{!!notice&&<View style={s.notice}><Ionicons name="checkmark-circle" size={18} color={colors.successText}/><Text style={s.noticeText}>{notice}</Text><Pressable onPress={()=>setNotice("")}><Ionicons name="close" size={17} color={colors.successText}/></Pressable></View>}<View style={s.options}>{choices.map(choice=>{const active=selected===choice.value;return <Pressable key={choice.value} disabled={saving} onPress={()=>{setSelected(choice.value);setNotice("")}} accessibilityRole="radio" accessibilityState={{checked:active,disabled:saving}} style={({pressed})=>[s.option,active&&s.optionOn,pressed&&s.pressed,saving&&s.disabled]}>{active&&<View style={s.check}><Ionicons name="checkmark" size={14} color={colors.white}/></View>}<View style={[s.emojiBox,active&&s.emojiBoxOn]}><Text style={s.emoji}>{choice.icon}</Text></View><View style={s.flex}><Text style={[s.optionTitle,active&&s.optionTitleOn]}>{t(`onboarding.shopType.${choice.value}`)}</Text><Text style={s.optionDescription}>{t(`onboarding.shopType.${choice.value}Desc`)}</Text><View style={s.channelRow}>{choice.channels.map(channel=><View key={channel} style={[s.channel,active&&s.channelOn]}><Ionicons name={channel==="ONLINE"?"globe-outline":channel==="POS"?"barcode-outline":"bag-handle-outline"} size={11} color={active?colors.primaryDark:colors.secondary}/><Text style={[s.channelText,active&&s.channelTextOn]}>{t(`onboarding.channel.${channel}`)}</Text></View>)}</View></View></Pressable>})}</View><View style={s.onlineNote}><Ionicons name="information-circle-outline" size={18} color={colors.info}/><Text style={s.onlineNoteText}>{t("onboarding.shopType.onlineNote")}</Text></View>{!!error&&<View style={s.error}><Ionicons name="alert-circle-outline" size={17} color={colors.danger}/><Text style={s.errorText}>{error}</Text></View>}<Pressable disabled={!selected||saving} onPress={()=>void save()} style={[s.save,(!selected||saving)&&s.disabled]}>{saving?<ActivityIndicator color={colors.white}/>:<><Ionicons name="save-outline" size={18} color={colors.white}/><Text style={s.saveText}>{t("common.save")}</Text></>}</Pressable></ScrollView></View>
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},header:{minHeight:65,flexDirection:"row",alignItems:"center",gap:10,borderBottomWidth:1,borderBottomColor:colors.divider,backgroundColor:colors.white,paddingHorizontal:14},headerIcon:{width:40,height:40,borderRadius:12,alignItems:"center",justifyContent:"center",backgroundColor:colors.primaryLight},flex:{flex:1,minWidth:0},title:{fontSize:16,fontWeight:"800",color:colors.heading},headerSubtitle:{fontSize:9,color:colors.muted,marginTop:2},content:{padding:14,paddingBottom:35,gap:12},intro:{gap:4},introTitle:{fontSize:14,fontWeight:"800",color:colors.heading},introText:{fontSize:10,lineHeight:15,color:colors.secondary},notice:{flexDirection:"row",alignItems:"center",gap:7,borderRadius:10,backgroundColor:colors.successBackground,padding:10},noticeText:{flex:1,fontSize:10,fontWeight:"600",color:colors.successText},options:{gap:10},option:{position:"relative",minHeight:106,flexDirection:"row",alignItems:"flex-start",gap:11,borderWidth:2,borderColor:colors.divider,borderRadius:16,backgroundColor:colors.white,padding:13},optionOn:{borderColor:colors.activeBorder,backgroundColor:colors.cardSecondary},pressed:{opacity:.76},check:{position:"absolute",zIndex:2,top:9,right:9,width:22,height:22,borderRadius:11,alignItems:"center",justifyContent:"center",backgroundColor:colors.primary},emojiBox:{width:45,height:45,borderRadius:13,alignItems:"center",justifyContent:"center",backgroundColor:colors.disabled},emojiBoxOn:{backgroundColor:colors.primaryLight},emoji:{fontSize:23},optionTitle:{fontSize:12,fontWeight:"800",color:colors.heading,paddingRight:24},optionTitleOn:{color:colors.primaryDark},optionDescription:{fontSize:9,lineHeight:14,color:colors.secondary,marginTop:4,paddingRight:13},channelRow:{flexDirection:"row",flexWrap:"wrap",gap:5,marginTop:8},channel:{flexDirection:"row",alignItems:"center",gap:3,borderRadius:8,backgroundColor:colors.disabled,paddingHorizontal:6,paddingVertical:4},channelOn:{backgroundColor:colors.primaryLight},channelText:{fontSize:7,fontWeight:"600",color:colors.secondary},channelTextOn:{color:colors.primaryDark},onlineNote:{flexDirection:"row",alignItems:"flex-start",gap:7,borderRadius:11,backgroundColor:colors.infoBackground,padding:11},onlineNoteText:{flex:1,fontSize:9,lineHeight:14,color:colors.infoText},error:{flexDirection:"row",alignItems:"center",gap:7,borderRadius:10,backgroundColor:colors.dangerBackground,padding:10},errorText:{flex:1,fontSize:9,color:colors.dangerText},save:{minHeight:50,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:7,borderRadius:13,backgroundColor:colors.primary},saveText:{fontSize:12,fontWeight:"800",color:colors.white},disabled:{opacity:.48}});
